env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  RUNNING_ON_CI: "true"
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  PUBLISH_APPS: "true"
  GITHUB_PACKAGES_USERNAME: ${{ github.actor }}
  GITHUB_PACKAGES_PASSWORD: ${{ secrets.ACCESS_TOKEN }}
  
on: [push]

jobs:
  build:
    name: Build and test (JDK ${{ matrix.java_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: ["11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            repository: 'Digitaler-Impfnachweis/covpass-android'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
          distribution: adopt
      - name: Configure Gradle
        run: ./gradlew help
      - name: Build project
        run: ./gradlew assemble
